---
kind: BuildConfig
apiVersion: build.danopia.net/v1
metadata:
  name: kubernetes-node-crds
spec:
  triggers:
  - type: ConfigChange
  - type: ImageChange
  source:
    type: Git
    git:
      uri: https://github.com/danopia/kubernetes-operators
    contextDir: cloudydeno.github.io
  strategy:
    type: Docker
  output:
    to:
      kind: DockerImage
      name: kubernetes-node-crds
