// Autogenerated Schema file for CloudydenoGithubIoV1
import * as c from "https://deno.land/x/kubernetes_apis@v0.3.2/common.ts";

import * as MetaV1 from "https://deno.land/x/kubernetes_apis@v0.3.2/builtin/meta@v1/structs.ts";
type ListOf<T> = {
  metadata: MetaV1.ListMeta;
  items: Array<T>;
};

export interface BlockDevice {
  apiVersion?: "cloudydeno.github.io/v1";
  kind?: "BlockDevice";
  spec: {
    nodeName: string;
    devicePath: string;
    deviceModel?: string | null;
    serialNumber?: string | null;
    userCapacity: number;
    userCapacityHuman?: string | null;
    logicalSectorSize?: number | null;
    physicalSectorSize?: number | null;
    rotationRate?: c.IntOrString | null;
    formFactor?: string | null;
  };
  status?: {
    sataStatus: string;
    smartEnabled: boolean;
    smartReport?: {
      collectionTime: c.Time;
      overallAssessment: string;
      attributes: Array<{
        id?: number | null;
        name?: string | null;
        currentHealth?: number | null;
        worstHealth?: number | null;
        threshold?: number | null;
        type?: string | null;
        rawValue?: string | null;
      }>;
      errors: Array<string>;
    } | null;
  } | null;
  metadata?: MetaV1.ObjectMeta | null;
}
export function toBlockDevice(input: c.JSONValue): BlockDevice & c.ApiKind {
  const obj = c.checkObj(input);
  return {
    ...c.assertOrAddApiVersionAndKind(obj, "cloudydeno.github.io/v1", "BlockDevice"),
    spec: toBlockDevice_spec(obj["spec"]),
    status: c.readOpt(obj["status"], toBlockDevice_status),
    metadata: c.readOpt(obj["metadata"], MetaV1.toObjectMeta),
  }}
export function fromBlockDevice(input: BlockDevice): c.JSONValue {
  return {
    ...c.assertOrAddApiVersionAndKind(input, "cloudydeno.github.io/v1", "BlockDevice"),
    ...input,
    status: input.status != null ? {
      ...input.status,
      smartReport: input.status.smartReport != null ? {
        ...input.status.smartReport,
        collectionTime: input.status.smartReport.collectionTime != null ? c.fromTime(input.status.smartReport.collectionTime) : undefined,
      } : undefined,
    } : undefined,
    metadata: input.metadata != null ? MetaV1.fromObjectMeta(input.metadata) : undefined,
  }}
export function toBlockDevice_spec(input: c.JSONValue) {
  const obj = c.checkObj(input);
  return {
    nodeName: c.checkStr(obj["nodeName"]),
    devicePath: c.checkStr(obj["devicePath"]),
    deviceModel: c.readOpt(obj["deviceModel"], c.checkStr),
    serialNumber: c.readOpt(obj["serialNumber"], c.checkStr),
    userCapacity: c.checkNum(obj["userCapacity"]),
    userCapacityHuman: c.readOpt(obj["userCapacityHuman"], c.checkStr),
    logicalSectorSize: c.readOpt(obj["logicalSectorSize"], c.checkNum),
    physicalSectorSize: c.readOpt(obj["physicalSectorSize"], c.checkNum),
    rotationRate: c.readOpt(obj["rotationRate"], c.toIntOrString),
    formFactor: c.readOpt(obj["formFactor"], c.checkStr),
  }}
export function toBlockDevice_status(input: c.JSONValue) {
  const obj = c.checkObj(input);
  return {
    sataStatus: c.checkStr(obj["sataStatus"]),
    smartEnabled: c.checkBool(obj["smartEnabled"]),
    smartReport: c.readOpt(obj["smartReport"], toBlockDevice_status_smartReport),
  }}
export function toBlockDevice_status_smartReport(input: c.JSONValue) {
  const obj = c.checkObj(input);
  return {
    collectionTime: c.toTime(obj["collectionTime"]),
    overallAssessment: c.checkStr(obj["overallAssessment"]),
    attributes: c.readList(obj["attributes"], toBlockDevice_status_smartReport_attributes),
    errors: c.readList(obj["errors"], c.checkStr),
  }}
export function toBlockDevice_status_smartReport_attributes(input: c.JSONValue) {
  const obj = c.checkObj(input);
  return {
    id: c.readOpt(obj["id"], c.checkNum),
    name: c.readOpt(obj["name"], c.checkStr),
    currentHealth: c.readOpt(obj["currentHealth"], c.checkNum),
    worstHealth: c.readOpt(obj["worstHealth"], c.checkNum),
    threshold: c.readOpt(obj["threshold"], c.checkNum),
    type: c.readOpt(obj["type"], c.checkStr),
    rawValue: c.readOpt(obj["rawValue"], c.checkStr),
  }}

export interface BlockDeviceList extends ListOf<BlockDevice> {
  apiVersion?: "cloudydeno.github.io/v1";
  kind?: "BlockDeviceList";
};
export function toBlockDeviceList(input: c.JSONValue): BlockDeviceList & c.ApiKind {
  const obj = c.checkObj(input);
  return {
    ...c.assertOrAddApiVersionAndKind(obj, "cloudydeno.github.io/v1", "BlockDeviceList"),
    metadata: MetaV1.toListMeta(obj.metadata),
    items: c.readList(obj.items, toBlockDevice),
  }}
