---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: build-operator-loop
spec:
  replicas: 1
  revisionHistoryLimit: 1
  template:
    spec:
      serviceAccountName: build-operator
      containers:
      - name: loop
        image: build-operator

        resources:
          requests:
            cpu: 10m
            memory: 125Mi
          limits:
            cpu: 250m
            memory: 125Mi
