---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: loop-blockdevices
spec:

  updateStrategy:
    type: RollingUpdate

  template:
    spec:

      serviceAccountName: loop-blockdevices

      containers:

      - name: loop
        image: kube-pet-loop-blockdevice

        securityContext:
          # capabilities:
          #   add:
          #   - CAP_SYS_RAWIO
          #   - CAP_SYS_ADMIN
          #   - CAP_SYS_RESOURCE
          seLinuxOptions:
            type: unconfined_t
          # TODO: is this hard required?
          privileged: true

        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName

        args:
        - sh
        - -euxc
        - |
          while date
          do deno run \
              --allow-run=smartctl \
              --allow-read=/var/run/secrets/kubernetes.io/serviceaccount \
              --allow-net=kubernetes.default.svc.cluster.local \
              --unstable \
              --cached-only \
              /app/lib/BlockDevice/mod.ts \
              $NODE_NAME \
          || echo "Failed!"
          sleep 3600
          done

        resources:
          requests:
            memory: 40Mi
            cpu: 25m
          limits:
            memory: 40Mi
            cpu: 100m

        volumeMounts:
        - name: dev
          mountPath: /dev

      volumes:
      - name: dev
        hostPath:
          path: /dev
          # type: Directory
