apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-crds:blockdevices:view
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
- apiGroups:
  - cloudydeno.github.io
  resources:
  - blockdevices
  verbs:
  - get
  - list
  - watch
