---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-crds:blockdevices:loop
rules:
- apiGroups:
  - cloudydeno.github.io
  resources:
  - blockdevices
  verbs:
  - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-crds:blockdevices:loop
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: node-crds:blockdevices:loop
subjects:
- kind: ServiceAccount
  name: loop-blockdevices
  namespace: kube-pets # TODO: why isn't this being filled in?
